[package]
name = "grid-ray"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["glam"]
glam = ["ilattice/glam"]

[dependencies]
ilattice = { git = "https://github.com/bonsairobo/ilattice-rs", rev = "30b6b463", default-features = false }
